### ISSUE TITLE
Problems with amd64 build?

### ISSUE THREAD

**Issue by onitake** [ericoporto/agsjoy#1]
Is there a particular reason why you only support i386 for now?

I was able to build libagsjoy.so successfully on amd64 by just installing libsdl2-dev:
```
$ file libagsjoy.so 
libagsjoy.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a8ad0fb065e6572a7c72c71588639c1c0cb26edc, not stripped
```

This was on Debian buster (testing), however, not Ubuntu 16.04.

**Comment by ericoporto** [comment]
Hey @onitake I

I have the same output for file:

    $ file libagsjoy.so 
    libagsjoy.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=99cf8dea57a9854d1ecf52700ea4507868a7a229, not stripped

I understand this means this is a 64-bit binary. [I don't really know this and believed the voted answer here](https://superuser.com/questions/791506/how-to-determine-if-a-linux-binary-file-is-32-bit-or-64-bit).

What I couldn't find out, is how to build for a 32 bit system (i386) while I am using a 64 bit system. Unfortunately, I don't have a 32 bit computer anymore, so I was looking in a way to do this on my 64 bit machine (but all dependencies I tried to install, depended on more stuff until I got the "you have held broken packages" message).

This is why for now, I think it should be easier to create a virtual machine running some 32-bit Ubuntu to do it - I didn't had the time yet to do it though. 

Ah yes, this all require the user (player) has sdl2 installed or is playing the game through Steam.

**Comment by onitake** [comment]
Ah, I see now. I misinterpreted the README and thought only i386 was supported.

And I agree that cross-compiling on Debian/Ubuntu is a bit complicated.
The correct way to this would be to add the additional architecture to the system, then install dependencies using the appropriate arch tag. The compiler can then be launched with -m32 (or -m64 for 64bit cross-compilation).

Something like:
```
dpkg --add-architecture i386
apt update
apt install libsdl2-dev:i386
```
Note that libsdl2-dev does not support Multi-Arch properly, so you can only have the -dev files installed for either i386 or amd64. Other -dev packages handle this better.
